SELECT PERSON_ID, MIN(DRUG_EXPOSURE_START_DATE) AS WFR_first_date
	FROM DRUG_EXPOSURE
	WHERE DRUG_CONCEPT_ID IN (
		SELECT DESCENDANT_CONCEPT_ID
		FROM CONCEPT_ANCESTOR WHERE ANCESTOR_CONCEPT_ID = 1310149 /*warfarin*/
	)
	GROUP BY PERSON_ID;
